Table post {
  post_id uuid [pk]
  text varchar
}

Table post_tag {
  post_id uuid [pk, ref: > post.post_id]
  tag varchar [pk, ref: > tags.tag]
}

Table tags {
  tag varchar [pk, note:'タグにはサロゲートキーは不要と考えるためタグ名を主キーとする']
}